[project]
name = "slideagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "openai>=1.69.0",
    "openai-agents>=0.0.7",
    "pydantic>=2.11.0",
]
